### ISSUE TITLE
Incorrect url

### ISSUE THREAD

**Issue by MeesMaas** [saxionroosters/api#1]
The website http://api.saxionroosters.nl/explorer is still using http://api.saxionroosters.nl/v1/ while it should be http://api.saxionroosters.nl/v2/

**Comment by wesselperik** [comment]
Hi Mees,

The saxionroosters API is currently in development and uses the v1-endpoint (see the base-url in the footer of the API explorer). Where do you see a reference to a v2-endpoint?

**Comment by MeesMaas** [comment]
In teacher.vue in the web repository

**Comment by wesselperik** [comment]
Ah, I see. The URL there is api.roosters.saxion.nl/v2, not api.saxionroosters.nl/v2 😉
We know that this API doesn't work anymore (Saxion took it offline), we are busy updating the Android and iOS apps and finishing the website, so this will change to the new API endpoint somewhere in the upcoming weeks.
